# Generated by Django 4.2.4 on 2023-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_address1_user_address2_user_city_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_judge',
            field=models.BooleanField(default=False, verbose_name='judge status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='student status'),
        ),
    ]
