# Generated by Django 4.2.6 on 2023-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_submitted_application',
            field=models.BooleanField(default=False, verbose_name='has submitted application'),
        ),
    ]
