# Generated by Django 4.2.6 on 2023-11-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_has_submitted_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
