# Generated by Django 4.2.7 on 2023-11-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_has_submitted_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_judge',
        ),
    ]
