# Generated by Django 4.2.7 on 2023-12-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_is_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_submitted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
