# Generated by Django 4.2.4 on 2023-10-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import page.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField()),
                ('support_letter_1', models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('support_letter_2', models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
