# Generated by Django 4.2.4 on 2023-10-01 16:28

from django.db import migrations, models
import page.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step1',
            options={'verbose_name_plural': 'step1'},
        ),
        migrations.AlterField(
            model_name='step1',
            name='support_letter_1',
            field=models.FileField(storage=page.storage_backends.PrivateMediaStorage(location='self.user.id'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='step1',
            name='support_letter_2',
            field=models.FileField(storage=page.storage_backends.PrivateMediaStorage(location='self.user.id'), upload_to=''),
        ),
    ]
