# Generated by Django 4.2.4 on 2023-10-01 18:52

from django.db import migrations, models
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_step1_options_alter_step1_support_letter_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step1',
            name='support_letter_1',
            field=models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path),
        ),
        migrations.AlterField(
            model_name='step1',
            name='support_letter_2',
            field=models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path),
        ),
    ]
