# Generated by Django 4.2.4 on 2023-10-01 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0004_alter_step1_support_letter_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=160)),
                ('job_title', models.CharField(max_length=40)),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('reference_letter_1', models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path)),
                ('reference_letter_2', models.FileField(blank=True, null=True, storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Step1',
        ),
    ]
