# Generated by Django 4.2.4 on 2023-10-02 23:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_employmenthistory_delete_step1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_1_full_name', models.CharField(max_length=40)),
                ('parent_1_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('parent_1_address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('parent_1_address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('parent_1_city', models.CharField(max_length=1024, verbose_name='City')),
                ('parent_1_state', models.CharField(choices=[('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='MI', max_length=20)),
                ('parent_1_zip_code', models.CharField(max_length=12, verbose_name='ZIP')),
                ('parent_1_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('parent_1_place_of_employment', models.CharField(max_length=120)),
                ('parent_1_job_title', models.CharField(max_length=120)),
                ('parent_2_full_name', models.CharField(max_length=40)),
                ('parent_2_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('parent_2_address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1')),
                ('parent_2_address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('parent_2_city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='City')),
                ('parent_2_state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='MI', max_length=20, null=True)),
                ('parent_2_zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP')),
                ('parent_2_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
                ('parent_2_place_of_employment', models.CharField(blank=True, max_length=120, null=True)),
                ('parent_2_job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('total_household_income', models.CharField(choices=[('0-20000', '0 - 20000'), ('20000-40000', '20000 - 40000'), ('40000-60000', '40000 - 60000'), ('60000-80000', '60000 - 80000'), ('80000-100000', '80000 - 100000'), ('100000-120000', '100000 - 120000'), ('120000-140000', '120000 - 140000'), ('140000+', '140000+')], max_length=20)),
                ('siblings', models.CharField(max_length=140)),
                ('high_school', models.CharField(max_length=120)),
                ('high_school_city', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name_plural': 'Employment History'},
        ),
    ]
