# Generated by Django 4.2.4 on 2023-10-02 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0006_familyinformation_alter_employmenthistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyinformation',
            options={'verbose_name_plural': 'Family Information'},
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
