# Generated by Django 4.2.6 on 2023-11-06 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0011_household_parent1_parent2_temporarystorage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name_plural': 'Household'},
        ),
        migrations.AlterModelOptions(
            name='parent2',
            options={'verbose_name_plural': 'Parent 2 Information'},
        ),
        migrations.RemoveField(
            model_name='household',
            name='id',
        ),
        migrations.AddField(
            model_name='household',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
