# Generated by Django 4.2.7 on 2023-11-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0012_alter_household_options_alter_parent2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='state',
            field=models.CharField(default='MI', max_length=20),
        ),
    ]
