# Generated by Django 4.2.7 on 2023-11-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0014_rename_employmenthistory_studentemploymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='siblings',
        ),
        migrations.AddField(
            model_name='household',
            name='siblings_over_18',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='siblings_under_18',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
