# Generated by Django 4.2.7 on 2023-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_parent_remove_parent2_user_delete_parent1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_1_address1',
            field=models.CharField(max_length=35, verbose_name='Parent 1 Address line 1'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_1_address2',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Parent 1 Address line 2'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_1_city',
            field=models.CharField(max_length=30, verbose_name='Parent 1 City'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_1_email',
            field=models.EmailField(max_length=254, verbose_name='parent 1 email address'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_1_zip_code',
            field=models.CharField(max_length=12, verbose_name='Parent 1 ZIP'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_address1',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Parent 2 Address line 1'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_address2',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Parent 2 Address line 2'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Parent 2 City'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent 2 email address'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Parent 2 ZIP'),
        ),
    ]
