# Generated by Django 4.2.7 on 2023-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0018_alter_parent_parent_1_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentemploymenthistory',
            name='employer_name',
            field=models.CharField(max_length=120, verbose_name='Student Employer Name'),
        ),
        migrations.AlterField(
            model_name='studentemploymenthistory',
            name='job_title',
            field=models.CharField(max_length=40, verbose_name='Student Job Title'),
        ),
    ]
