# Generated by Django 4.2.7 on 2023-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0019_alter_studentemploymenthistory_employer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentemploymenthistory',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(verbose_name='Student Hours Per Week'),
        ),
    ]
