# Generated by Django 4.2.7 on 2023-11-12 14:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0020_alter_studentemploymenthistory_hours_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_2_address1',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Parent 2 Address line 1 (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_address2',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Parent 2 Address line 2 (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Parent 2 City (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent 2 Email Address (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_full_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Parent 2 Full Name (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_job_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Parent 2 Job Title (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US', verbose_name='Parent 2 Phone Number (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_place_of_employment',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Parent 2 Place of Employment (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='MI', max_length=20, null=True, verbose_name='Parent 2 State (if applicable)'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Parent 2 Zip Code (if applicable)'),
        ),
    ]
