# Generated by Django 4.2.7 on 2023-11-12 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_usersession'),
        ('scholarship', '0022_personalinformation_place_of_bith'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('name', models.CharField(default='None', max_length=120)),
                ('city', models.CharField(default='None', max_length=40)),
                ('graduation_date', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('major', models.CharField(default='None', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'High School',
            },
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='high_school',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='high_school_city',
        ),
    ]
