# Generated by Django 4.2.7 on 2023-11-13 00:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0023_highschool_remove_personalinformation_high_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCounselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Academic Counselor Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', verbose_name='Academic Counselor Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Academic Counselor Email Address')),
            ],
            options={
                'verbose_name_plural': 'Academic Counselor',
            },
        ),
        migrations.CreateModel(
            name='HonorOrAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor_or_award_1', models.CharField(blank=True, max_length=120, verbose_name='Honor or Award')),
                ('year_received_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Received')),
                ('description_1', models.TextField(blank=True, verbose_name='Description')),
                ('honor_or_award_2', models.CharField(blank=True, max_length=120, verbose_name='Honor or Award')),
                ('year_received_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Received')),
                ('description_2', models.TextField(blank=True, verbose_name='Description')),
                ('honor_or_award_3', models.CharField(blank=True, max_length=120, verbose_name='Honor or Award')),
                ('year_received_3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Received')),
                ('description_3', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=models.CharField(default='None', max_length=40, verbose_name='High School City'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='High School GPA'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='graduation_date',
            field=models.DateField(verbose_name='High School Graduation Date'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='major',
            field=models.CharField(default='None', max_length=120, verbose_name='High School Major'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='name',
            field=models.CharField(default='None', max_length=120, verbose_name='High School Name'),
        ),
    ]
