# Generated by Django 4.2.7 on 2023-11-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0024_academiccounselor_honororaward_alter_highschool_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honororaward',
            name='year_received_1_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year Received'),
        ),
        migrations.AddField(
            model_name='honororaward',
            name='year_received_2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year Received'),
        ),
        migrations.AddField(
            model_name='honororaward',
            name='year_received_3_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year Received'),
        ),
    ]
