# Generated by Django 4.2.7 on 2023-11-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0025_honororaward_year_received_1_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honororaward',
            name='year_received_1',
        ),
        migrations.RemoveField(
            model_name='honororaward',
            name='year_received_2',
        ),
        migrations.RemoveField(
            model_name='honororaward',
            name='year_received_3',
        ),
    ]
