# Generated by Django 4.2.7 on 2023-11-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0026_remove_honororaward_year_received_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_1', models.CharField(blank=True, max_length=120, verbose_name='Activity')),
                ('year_participated_1_date', models.DateField(blank=True, null=True, verbose_name='Year Participated')),
                ('hours_per_week_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hours Per Week')),
                ('description_1', models.TextField(blank=True, verbose_name='Description')),
                ('activity_2', models.CharField(blank=True, max_length=120, verbose_name='Activity')),
                ('year_participated_2_date', models.DateField(blank=True, null=True, verbose_name='Year Participated')),
                ('hours_per_week_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hours Per Week')),
                ('description_2', models.TextField(blank=True, verbose_name='Description')),
                ('activity_3', models.CharField(blank=True, max_length=120, verbose_name='Activity')),
                ('year_participated_3_date', models.DateField(blank=True, null=True, verbose_name='Year Participated')),
                ('hours_per_week_3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hours Per Week')),
                ('description_3', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Extra Curricular',
            },
        ),
    ]
