# Generated by Django 4.2.7 on 2023-11-14 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_remove_highschool_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='High School GPA'),
        ),
    ]
