# Generated by Django 4.2.7 on 2023-11-14 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_usersession'),
        ('scholarship', '0032_alter_highschool_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEmployment',
            fields=[
                ('employer_name', models.CharField(max_length=120, verbose_name='Employer Name')),
                ('job_title', models.CharField(max_length=40, verbose_name='Job Title')),
                ('hours_per_week', models.PositiveSmallIntegerField(verbose_name='Hours Per Week')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Current Emploument',
            },
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_1_place_of_employment',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Parent 1 Place of Employment'),
        ),
        migrations.DeleteModel(
            name='StudentEmploymentHistory',
        ),
    ]
