# Generated by Django 4.2.7 on 2023-11-14 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0033_currentemployment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccounselor',
            name='id',
        ),
        migrations.AddField(
            model_name='academiccounselor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
