# Generated by Django 4.2.7 on 2023-11-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0034_remove_academiccounselor_id_academiccounselor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraCurricular',
        ),
        migrations.DeleteModel(
            name='HonorOrAward',
        ),
    ]
