# Generated by Django 4.2.7 on 2023-11-14 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0035_delete_extracurricular_delete_honororaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('major', models.CharField(max_length=120)),
                ('career', models.CharField(max_length=120)),
                ('applied_for_1', models.CharField(max_length=60)),
                ('applied_for_2', models.CharField(blank=True, max_length=60, null=True)),
                ('applied_for_3', models.CharField(blank=True, max_length=60, null=True)),
                ('plan_to_attend', models.CharField(max_length=60)),
                ('savings', models.IntegerField(default=0, help_text='How much have you saved for college')),
                ('savings_guardian', models.IntegerField(default=0, help_text='How much have others (parents, grandparents, etc.) saved for your education')),
                ('financial_need', models.TextField(help_text='Describe your financial need for scholarship funds (very important - be very specific)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'College',
            },
        ),
    ]
