# Generated by Django 4.2.7 on 2023-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0036_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='applied_for_1',
            field=models.CharField(help_text='Colleges/Universities you have applied to', max_length=60),
        ),
        migrations.AlterField(
            model_name='college',
            name='applied_for_2',
            field=models.CharField(blank=True, help_text='Colleges/Universities you have applied to', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='applied_for_3',
            field=models.CharField(blank=True, help_text='Colleges/Universities you have applied to', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='career',
            field=models.CharField(help_text='Career/Profession (teacher, musician, lawyer, etc.)', max_length=120),
        ),
        migrations.AlterField(
            model_name='college',
            name='goal',
            field=models.TextField(help_text='Educational Goal'),
        ),
        migrations.AlterField(
            model_name='college',
            name='major',
            field=models.CharField(help_text='College Major', max_length=120),
        ),
        migrations.AlterField(
            model_name='college',
            name='plan_to_attend',
            field=models.CharField(help_text='College/University you plan to attend', max_length=60),
        ),
    ]
