# Generated by Django 4.2.7 on 2023-11-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0037_alter_college_applied_for_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('foster_care', models.BooleanField(default=False, help_text="Are you in the foster care system, or are you an emancipated minor? If so, please indicate yes (This answer does not impact the judging process. If this doesn't apply, please select no).")),
                ('challenges', models.TextField(blank=True, help_text='If you answered yes to the last question, please briefly describe the challenges you have faced in your educational journey because of your experiences in foster care or as an emancipated minor.', null=True)),
                ('other_scholarships', models.TextField(blank=True, help_text='Other scholarships you have applied for', null=True)),
                ('other_scholarships_awarded', models.TextField(blank=True, help_text='Scholarships/grants you have already been awarded (name, amount and period of time covered)', null=True)),
                ('plan_to_pay', models.TextField(help_text='If granted this award, how do you plan to pay for the rest of your educational costs?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Other',
            },
        ),
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.AlterField(
            model_name='college',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
