# Generated by Django 4.2.7 on 2023-11-14 21:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0038_other_remove_college_id_alter_college_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccounselor',
            name='email',
            field=models.EmailField(help_text='Enter email address of counselor who can verify academic information', max_length=254, verbose_name='Academic Counselor Email Address'),
        ),
        migrations.AlterField(
            model_name='academiccounselor',
            name='name',
            field=models.CharField(help_text='Enter name of counselor who can verify academic information', max_length=120, verbose_name='Academic Counselor Name'),
        ),
        migrations.AlterField(
            model_name='academiccounselor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number of counselor who can verify academic information', max_length=128, region='US', verbose_name='Academic Counselor Phone Number'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=models.CharField(default='None', help_text='City where High School is Located', max_length=40, verbose_name='High School City'),
        ),
    ]
