# Generated by Django 4.2.7 on 2023-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0039_alter_academiccounselor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='applied_for_1',
            field=models.CharField(help_text='College/University you have applied to', max_length=60),
        ),
        migrations.AlterField(
            model_name='college',
            name='applied_for_2',
            field=models.CharField(blank=True, help_text='College/University you have applied to', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='applied_for_3',
            field=models.CharField(blank=True, help_text='College/University you have applied to', max_length=60, null=True),
        ),
    ]
