# Generated by Django 4.2.7 on 2023-11-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0041_rename_savings_guardian_college_savings_by_guardian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentemployment',
            options={'verbose_name_plural': 'Current Employment'},
        ),
    ]
