# Generated by Django 4.2.7 on 2023-11-16 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_usersession'),
        ('scholarship', '0042_alter_currentemployment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('reference_letter_1', models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path)),
                ('reference_letter_2', models.FileField(blank=True, null=True, storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
