# Generated by Django 4.2.7 on 2023-11-16 01:05

from django.db import migrations, models
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0043_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='reference_letter_1',
            field=models.FileField(storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path_for_reference_letter_1),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='reference_letter_2',
            field=models.FileField(blank=True, null=True, storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path_for_reference_letter_2),
        ),
    ]
