# Generated by Django 4.2.7 on 2023-11-16 01:38

from django.db import migrations, models
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0044_alter_attachments_reference_letter_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachments',
            options={'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='attachments',
            name='essay',
            field=models.FileField(default='', storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path_for_essay),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachments',
            name='high_school_transcript',
            field=models.FileField(default='', storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path_for_high_school_transcript),
            preserve_default=False,
        ),
    ]
