# Generated by Django 4.2.7 on 2023-11-17 00:19

from django.db import migrations, models
import page.storage_backends
import scholarship.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0047_attachments_extracurricular_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='community_service_volunteer_activities',
            field=models.FileField(default='', storage=page.storage_backends.PrivateMediaStorage(), upload_to=scholarship.models.get_user_file_path_community_service_activities),
            preserve_default=False,
        ),
    ]
