# Generated by Django 4.2.7 on 2023-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0048_attachments_community_service_volunteer_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentemployment',
            name='employer_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Employer Name'),
        ),
        migrations.AlterField(
            model_name='currentemployment',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hours Per Week'),
        ),
        migrations.AlterField(
            model_name='currentemployment',
            name='job_title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Job Title'),
        ),
    ]
