# Generated by Django 4.2.7 on 2023-12-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0052_alter_other_foster_care_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
