# Generated by Django 4.2.7 on 2023-12-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0053_applicationstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstate',
            options={'verbose_name_plural': 'Application State'},
        ),
    ]
