services:
  web:
    build: "."
    container_name: rpsf-web
    depends_on:
      - db
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local

  db:
    image: postgres:latest
    container_name: rpsf-db
    environment:
      POSTGRES_USER: "rpsf"
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local