# Generated by Django 4.2.4 on 2023-08-06 17:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorpage',
            name='body',
            field=wagtail.fields.StreamField([('hero_image', wagtail.blocks.StructBlock([('hero_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('hero_heading', wagtail.blocks.CharBlock(help_text='40 character limit.', max_length=40, required=False)), ('hero_message', wagtail.blocks.CharBlock(help_text='240 character limit.', max_length=240, required=False)), ('hero_cta', wagtail.blocks.CharBlock(help_text='Text to display on Call to Action. 20 character limit.', max_length=20, required=False, verbose_name='Hero CTA'))], icon='image')), ('sponsor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock())], icon='image'))], default='', use_json_field=True),
        ),
    ]
