# Generated by Django 5.0.6 on 2024-06-30 21:27

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_youtube_embed', wagtail.blocks.StructBlock([('youtube_property_id', wagtail.blocks.CharBlock(max_length=11, required=True)), ('hero_message', wagtail.blocks.CharBlock(help_text='48 character limit.', max_length=48, required=False))], icon='media'))]),
        ),
    ]
