# Generated by Django 5.0.6 on 2024-06-30 22:13

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_youtube_embed', wagtail.blocks.StructBlock([('youtube_property_id', wagtail.blocks.CharBlock(max_length=11, required=True)), ('hero_message', wagtail.blocks.CharBlock(help_text='48 character limit.', max_length=48, required=False))], icon='media')), ('cta_block', wagtail.blocks.StructBlock([('cta_text', wagtail.blocks.CharBlock(help_text='244 character limit.', max_length=244)), ('button_text', wagtail.blocks.CharBlock(help_text='25 character limit.', max_length=25)), ('internal_link', wagtail.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.blocks.URLBlock(required=False))], icon='placeholder'))]),
        ),
    ]
